import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildApp, createContext } from '../src/index.js';

let root: string;
let app: Awaited<ReturnType<typeof buildApp>>;
const H = { host: '127.0.0.1:0' };
const yaml = `version: 1
id: whatever
name: Bearer token demo
description: Sets bearer auth on a request.
feature: request-execution
supportedOutputs: [screenshots]
fixture:
  source: inline
  collection:
    name: Auth Demo
    requests:
      - name: Secure
        url: "{{baseUrl}}/secure"
        auth: { type: bearer, token: tok }
    environments:
      - name: Demo
        variables: [{ name: baseUrl, value: https://example.test }]
steps:
  - action: workspace.open
  - action: collection.open
    params: { name: Auth Demo }
  - action: request.open
    params: { name: Secure }
  - action: request.setAuth
    params: { mode: bearer, token: tok }
  - capture: { id: auth-configured, name: Bearer set }
`;

beforeAll(async () => {
  root = await mkdtemp(path.join(os.tmpdir(), 'bru-capture-gen-'));
  app = await buildApp(await createContext({ root }), { serveWeb: false });
  await app.ready();
});
afterAll(async () => { await app.close(); await rm(root, { recursive: true, force: true }); });

describe('Phase 9 generated workflows API', () => {
  it('GET /api/capabilities carries the composition vocabulary', async () => {
    const r = await app.inject({ method: 'GET', url: '/api/capabilities', headers: H });
    const body = r.json();
    expect(body.actions.map((a: { id: string }) => a.id)).toEqual(expect.arrayContaining(['ui.click', 'request.create', 'request.setAuth', 'collection.create', 'runner.open']));
    expect(body.states.map((s: { id: string }) => s.id)).toContain('response.received');
    expect(body.regions.map((s: { id: string }) => s.id)).toContain('response.body');
    expect(body.fixtures.map((f: { path: string }) => f.path)).toContain('request-execution/jsonplaceholder');
    expect(body.testIds.length).toBeGreaterThan(400);
    const click = body.actions.find((a: { id: string }) => a.id === 'ui.click');
    expect(click.params.properties.testId).toBeDefined();
    expect(JSON.stringify(body)).not.toMatch(/\[data-testid=/);
  });
  it('validates definitions against the schema and the action registry', async () => {
    const ok = await app.inject({ method: 'POST', url: '/api/workflows/validate', headers: H, payload: { yaml } });
    expect(ok.json()).toMatchObject({ valid: true, stepCount: 5, captureIds: ['auth-configured'] });
    const bad = await app.inject({ method: 'POST', url: '/api/workflows/validate', headers: H, payload: { yaml: yaml.replace('request.setAuth', 'request.setAuthz').replace('mode: bearer', 'mode: bearer') } });
    expect(bad.json().valid).toBe(false); expect(bad.json().issues[0].message).toMatch(/unknown action/);
    const badParams = await app.inject({ method: 'POST', url: '/api/workflows/validate', headers: H, payload: { yaml: yaml.replace('mode: bearer', 'mode: magic') } });
    expect(badParams.json().valid).toBe(false); expect(badParams.json().issues[0].path).toBe('steps.3.params.mode');
    expect((await app.inject({ method: 'POST', url: '/api/workflows/validate', headers: H, payload: { yaml: 'a: [' } })).statusCode).toBe(400);
  });
  it('saves, lists as source generated, edits and deletes', async () => {
    const saved = await app.inject({ method: 'POST', url: '/api/workflows/generated', headers: H, payload: { yaml, prompt: 'show bearer auth', provider: 'anthropic', model: 'm' } });
    expect(saved.statusCode).toBe(201);
    const { id, valid } = saved.json();
    expect(valid).toBe(true); expect(id).toMatch(/^bearer-token-demo-[a-z0-9]{6}$/);
    const list = (await app.inject({ method: 'GET', url: '/api/workflows', headers: H })).json().workflows;
    const mine = list.find((w: { id: string }) => w.id === id);
    expect(mine.source).toBe('generated'); expect(mine.summary.fixture).toEqual({ source: 'inline', collection: { name: 'Auth Demo' } });
    const one = (await app.inject({ method: 'GET', url: `/api/workflows/${id}`, headers: H })).json();
    expect(one.rawText).toContain('# Generated by Bruno Capture'); expect(one.rawText).toContain('show bearer auth');
    const caps = (await app.inject({ method: 'GET', url: '/api/capabilities', headers: H })).json();
    expect(caps.workflows.find((w: { id: string }) => w.id === id).source).toBe('generated');

    const edited = one.rawText.replace('name: Bearer token demo', 'name: Bearer token demo (edited)');
    expect((await app.inject({ method: 'PUT', url: `/api/workflows/generated/${id}`, headers: H, payload: { yaml: edited.replace(`id: ${id}`, 'id: other-id') } })).statusCode).toBe(400);
    const put = await app.inject({ method: 'PUT', url: `/api/workflows/generated/${id}`, headers: H, payload: { yaml: edited } });
    expect(put.statusCode).toBe(200);
    expect((await app.inject({ method: 'GET', url: `/api/workflows/${id}`, headers: H })).json().summary.name).toBe('Bearer token demo (edited)');

    expect((await app.inject({ method: 'DELETE', url: `/api/workflows/generated/${id}`, headers: H })).json()).toEqual({ removed: id });
    expect((await app.inject({ method: 'GET', url: `/api/workflows/${id}`, headers: H })).statusCode).toBe(404);
    expect((await app.inject({ method: 'DELETE', url: '/api/workflows/generated/runner-collection-run', headers: H })).statusCode).toBe(404);
  });
  it('rejects invalid definitions on save with the issues', async () => {
    const r = await app.inject({ method: 'POST', url: '/api/workflows/generated', headers: H, payload: { yaml: yaml.replace('request.setAuth', 'nope.x') } });
    expect(r.statusCode).toBe(400); expect(r.json().error.code).toBe('workflow_invalid');
  });
});
