import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ulid } from 'ulid';
import { Document } from 'yaml';
import { WorkflowDefinitionSchema, type WorkflowDefinition, type WorkflowDefinitionInput } from '@bruno-capture/shared';

export interface SavedGeneratedWorkflow { id: string; file: string; yaml: string; definition: WorkflowDefinition }

/** kebab-case slug from a human name, capped. */
export function slugifyName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40).replace(/-+$/, '') || 'workflow';
}

/** Definition → YAML text with a provenance header comment. Deterministic key order (as authored). */
export function definitionToYaml(def: WorkflowDefinitionInput | WorkflowDefinition, header?: string): string {
  const clean = JSON.parse(JSON.stringify(def)) as Record<string, unknown>;
  const doc = new Document(clean);
  if (header) doc.commentBefore = ` ${header.split('\n').join('\n ')}`;
  return doc.toString({ lineWidth: 0 });
}

/**
 * Phase 9: composed workflows live as ordinary YAML files under
 * `<app support>/workflows/generated/`, so the registry lists them, the watcher sees edits,
 * Regenerate Exact/Latest work and a user can promote one into a custom directory by moving the file.
 */
export class GeneratedWorkflowStore {
  constructor(readonly dir: string) {}

  /** Give the definition a unique id derived from its name and write it. */
  async save(input: WorkflowDefinitionInput, opts: { prompt?: string; provider?: string; model?: string } = {}): Promise<SavedGeneratedWorkflow> {
    const base = slugifyName(input.name);
    const id = `${base}-${ulid().slice(-6).toLowerCase()}`;
    const definition = WorkflowDefinitionSchema.parse({ ...input, id });
    const header = [
      `Generated by Bruno Capture on ${new Date().toISOString()}`,
      opts.prompt ? `from the prompt: ${opts.prompt.replace(/\s+/g, ' ').slice(0, 300)}` : undefined,
      opts.provider ? `planner: ${opts.provider}${opts.model ? ` · ${opts.model}` : ''}` : undefined,
      'Edit freely — this file is registered like any other workflow.',
    ].filter(Boolean).join('\n');
    const yaml = definitionToYaml({ ...input, id }, header);
    await mkdir(this.dir, { recursive: true });
    const file = path.join(this.dir, `${id}.yaml`);
    await writeFile(file, yaml, 'utf8');
    return { id, file, yaml, definition };
  }

  /** Rewrite an existing generated file (e.g. after self-healing learned better steps). Keeps the header. */
  async update(file: string, definition: WorkflowDefinition, note?: string): Promise<string> {
    if (path.resolve(path.dirname(file)) !== path.resolve(this.dir)) throw new Error(`refusing to rewrite a workflow outside the generated directory: ${file}`);
    let header: string | undefined;
    try {
      const prev = await readFile(file, 'utf8');
      header = prev.split('\n').filter((l) => l.startsWith('#')).map((l) => l.replace(/^#\s?/, '')).join('\n') || undefined;
    } catch { /* new file */ }
    if (note) header = `${header ? header + '\n' : ''}${note}`;
    const yaml = definitionToYaml(definition, header);
    await writeFile(file, yaml, 'utf8');
    return yaml;
  }

  async delete(id: string): Promise<boolean> {
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(id)) return false;
    const file = path.join(this.dir, `${id}.yaml`);
    try { await rm(file); return true; } catch { return false; }
  }

  fileFor(id: string): string { return path.join(this.dir, `${id}.yaml`); }
}
